### PR TITLE
navbar done

### PR DESCRIPTION
**Pull request by Mhizdhee**

### CODE REVIEW

**Review by honour-dev — COMMENTED** [review]
1. i feel like the use of rem and em makes a work more responsive than using px (there's no need to change it though).
2. your signup button doesn't have a hover effect.
other than these, your work is nice.

**Review by honour-dev — APPROVED** [review]
1. i feel like the use of rem and em makes a work more responsive than using px (there's no need to change it though).
2. your signup button doesn't have a hover effect.
other than these, your work is nice.

**Review by eappiah56 — DISMISSED** [review]
i checked your work and i must say, you have done a good work but i think you should add hover effect to your sign up button

**Review by honour-dev — APPROVED** [review]
good work!!

**Review by eappiah56 — COMMENTED** [review]
great

**Pull request merged**
